### PR TITLE
Sprint 2 branch

### PR DESCRIPTION
**Pull request by Louisdrejer**

### CODE REVIEW

**Comment by FrancaSun** [comment]
N.B.: login with Louis as username and  louis1234 as password

**Comment by mircealungu** [comment]
why is this merged? shouldn't you wait for us to review it?

**Comment by Haiduri98** [comment]
Hi Mircea,

it was a mistake, I did it without paying attention that it was the wrong branch.

Best regards,
Haidar



Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Haiduri98** [comment]
Hi Mircea,

it was a mistake, I did it without paying attention that it was the wrong branch.

Best regards,
Haidar



Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
